### ISSUE TITLE
Make E10S compatible

### ISSUE THREAD

**Issue by digitarald** [mozilla/interest-dashboard#54]
In a performance survey we saw this addon was installed for a few Mozillians and blocked them from getting E10S. There seems to be no good story for sunsetting addons, especially impacts interesting experiments like this one.

As a short term solution, could you submit an update to AMO with this addon being marked e10s compatible? The other solution might be that the addon could just be marked incompatible with newer Firefox versions.

/cc @emtwo @Mardak

**Comment by tspurway** [comment]
I think deprecating or removing the addon for AMO might be the best direction to go with this.  It was a useful experiment, but we aren't prepared or willing to maintain it further.

**Comment by digitarald** [comment]
> I think deprecating or removing the addon for AMO might be the best direction to go with this.

I agree that it should not acquire new users. Does that fix existing installations though?

**Comment by overholt** [comment]
@jvillalobos or @andymckay could probably tell us if removing it from AMO would deal with existing installations.

**Comment by emtwo** [comment]
Adding cpeterson in CC,

In another email thread he mentioned that the problem will just go away in
Firefox ~54 when we will stop loading add-ons that are not explicitly
marked as multi-process compatible on AMO.

Could we go down this path instead as there are currently no resources or
reason to maintain it?

-Marina

**Comment by overholt** [comment]
I personally think 54 is too far away.

**Comment by digitarald** [comment]
Just to put some more background on impact: This add on was installed by
our most engaged users that are interested in privacy and wanting to help
us to improve our interest matching efforts. A lot of them, including
Mozilla employees, still have it installed as few users actively curate
their installed add on list.

By not getting this now-legacy add on off their systems we will block them
from a quality Firefox experience (e10s!) for 3 more Firefox versions, 4.5
months.

**Comment by jvillalobos** [comment]
Removing it from AMO is a good idea, but that doesn't impact existing installations.

If the add-on has been discontinued, we can mark it as incompatible for 51 and above (or some other version). Let me know what works for you.

**Comment by digitarald** [comment]
That seems to be the easiest way for this and similar addons without maintainers. We don't want to waste resources on cleaning up if there is an easy way.

@jvillalobos how reliable does the incompatible version disables the addon? I heard people mention that we relaxed the max version.

**Comment by jvillalobos** [comment]
It's reliable. We introduced the admin compatibility override precisely because Firefox doesn't check the max version.

**Comment by cpeterso** [comment]
We should mark the add-on as incompatible, as @jvillalobos suggests, instead of waiting four months for 54.

**Comment by digitarald** [comment]
@jvillalobos who can own marking this addon incompatible?

**Comment by jvillalobos** [comment]
I can do it right now if we're all in agreement.

**Comment by jvillalobos** [comment]
And you would also want the AMO listing to be disabled, right?

**Comment by overholt** [comment]
@emtwo, can you confirm we're good to go with @jvillalobos' proposed changes?

**Comment by emtwo** [comment]
Yes please go ahead and mark the addon as incompatible and disabled. Thank
you!

-Marina

**Comment by jvillalobos** [comment]
Done.
